// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Neighborhood.DataBaseContext;

namespace Neighborhood.Migrations
{
    [DbContext(typeof(NeighborhoodContext))]
    [Migration("20210428232141_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.1.21102.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Neighborhood.Models.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Santa Fe 1",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Santa Fe 2",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "Santa Fe 3",
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 4,
                            Address = "Santa Fe 4",
                            OwnerId = 3
                        },
                        new
                        {
                            Id = 5,
                            Address = "Santa Fe 5",
                            OwnerId = 4
                        },
                        new
                        {
                            Id = 6,
                            Address = "Santa Fe 6",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 7,
                            Address = "Santa Fe 7",
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 8,
                            Address = "Santa Fe 8",
                            OwnerId = 1
                        });
                });

            modelBuilder.Entity("Neighborhood.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Karina",
                            Phone = "987654321"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Marissa",
                            Phone = "123456789"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Mayte",
                            Phone = "987654322"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Cristina",
                            Phone = "987654323"
                        });
                });

            modelBuilder.Entity("Neighborhood.Models.House", b =>
                {
                    b.HasOne("Neighborhood.Models.Owner", "Owner")
                        .WithMany("Houses")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Neighborhood.Models.Owner", b =>
                {
                    b.Navigation("Houses");
                });
#pragma warning restore 612, 618
        }
    }
}
